/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dictionary;

import Constantes.Const;
import Constantes.Expressions;
import Database.DAO;
import Users.NewUserFrame;
import Users.UserFrame;
import Users.UserInstance;
import Users.UserNewPassword;
import Utils.Utilities;
import com.mysql.cj.jdbc.result.ResultSetMetaData;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;
import sun.java2d.SunGraphicsEnvironment;

/**
 *
 * @author gbartholomeu
 */
public class DictionaryFrame extends javax.swing.JFrame {

    private final JFrame parentFrame;
    private final static Logger LOGGER = Logger.getLogger(DictionaryFrame.class.getName());

    private String selectedCard = "cardGrid";
    private CardLayout cardLayout = null;

    private boolean isEditingMode = false;
    private boolean isCreatingMode = false;
    private char searchMode = 'A';

    private final TableCellRenderer tableCellRenderer = new DefaultTableCellRenderer() {

        SimpleDateFormat f = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");

        @Override
        public Component getTableCellRendererComponent(JTable table,
                Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            if (value instanceof Date) {
                value = f.format(value);
            }
            if (value instanceof Boolean) {
                JCheckBox isActive = new JCheckBox();
                isActive.setSelected((Boolean) value);
                return isActive;
            }

            return super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
        }
    };

    /**
     * Creates new form DictionaryFrame
     *
     * @param parentFrame
     */
    public DictionaryFrame(JFrame parentFrame) {
        initComponents();
        turnOffTableEditable();
        controlEditButton();
        this.parentFrame = parentFrame;
    }

    private void turnOffTableEditable() {
        getTblObjectHistory().setDefaultEditor(Object.class, null);
        getTblObjects().setDefaultEditor(Object.class, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        auxJPM = new javax.swing.JPopupMenu();
        createTemplateJMI = new javax.swing.JMenuItem();
        separador1JS = new javax.swing.JPopupMenu.Separator();
        insertIfJMI = new javax.swing.JMenuItem();
        insertIfElseJMI = new javax.swing.JMenuItem();
        separador2JS = new javax.swing.JPopupMenu.Separator();
        validateObject = new javax.swing.JMenuItem();
        objectsJPM = new javax.swing.JPopupMenu();
        filtersJMenu = new javax.swing.JMenu();
        allJMI = new javax.swing.JMenuItem();
        onlyActiveJMI = new javax.swing.JMenuItem();
        onlyInactiveJMI = new javax.swing.JMenuItem();
        pnlMain = new javax.swing.JPanel();
        tbdpanelMain = new javax.swing.JTabbedPane();
        pnlGrid = new javax.swing.JPanel();
        pnlGridView = new javax.swing.JPanel();
        scrpnlGrid = new javax.swing.JScrollPane();
        tblObjects = new javax.swing.JTable();
        pnlDetailView = new javax.swing.JPanel();
        pnlInformation = new javax.swing.JPanel();
        pnlSQLInformation = new javax.swing.JPanel();
        lblObjectName = new javax.swing.JLabel();
        txtObjectName = new javax.swing.JTextField();
        lblObjectType = new javax.swing.JLabel();
        cmbBoxObjectType = new javax.swing.JComboBox<>();
        lblObjectDate = new javax.swing.JLabel();
        txtObjectDate = new javax.swing.JTextField();
        lblObjectUser = new javax.swing.JLabel();
        txtObjectUser = new javax.swing.JTextField();
        pnlSQL = new javax.swing.JPanel();
        scrpnlDetail = new javax.swing.JScrollPane();
        txtareaSQL = new javax.swing.JTextArea();
        jToolBar1 = new javax.swing.JToolBar();
        pnlHistory = new javax.swing.JPanel();
        pnlObjectHistory = new javax.swing.JPanel();
        scrpnlHistoryGrid = new javax.swing.JScrollPane();
        tblObjectHistory = new javax.swing.JTable();
        scrpnlHistoryContent = new javax.swing.JScrollPane();
        txtareaHistoryContent = new javax.swing.JTextArea();
        pnlButtons = new javax.swing.JPanel();
        btnNew = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnUndo = new javax.swing.JButton();
        btnDetail = new javax.swing.JButton();
        btnInactivate = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        menuUser = new javax.swing.JMenu();
        menuItemUser = new javax.swing.JMenuItem();
        menuPassword = new javax.swing.JMenuItem();

        createTemplateJMI.setText("Criar com template");
        createTemplateJMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createTemplateJMIActionPerformed(evt);
            }
        });
        auxJPM.add(createTemplateJMI);
        auxJPM.add(separador1JS);

        insertIfJMI.setText("Inserir cláusula IF");
        insertIfJMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertIfJMIActionPerformed(evt);
            }
        });
        auxJPM.add(insertIfJMI);

        insertIfElseJMI.setText("Inserir cláusula IF/ELSE");
        insertIfElseJMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertIfElseJMIActionPerformed(evt);
            }
        });
        auxJPM.add(insertIfElseJMI);
        auxJPM.add(separador2JS);

        validateObject.setText("Validar objeto");
        validateObject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validateObjectActionPerformed(evt);
            }
        });
        auxJPM.add(validateObject);

        filtersJMenu.setText("Filtros");

        allJMI.setText("Todos os objetos");
        allJMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allJMIActionPerformed(evt);
            }
        });
        filtersJMenu.add(allJMI);

        onlyActiveJMI.setText("Apenas ativos");
        onlyActiveJMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onlyActiveJMIActionPerformed(evt);
            }
        });
        filtersJMenu.add(onlyActiveJMI);

        onlyInactiveJMI.setText("Apenas inativos");
        onlyInactiveJMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onlyInactiveJMIActionPerformed(evt);
            }
        });
        filtersJMenu.add(onlyInactiveJMI);

        objectsJPM.add(filtersJMenu);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frmDictionary"); // NOI18N

        pnlMain.setLayout(new java.awt.BorderLayout());

        tbdpanelMain.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tbdpanelMainStateChanged(evt);
            }
        });

        pnlGrid.setLayout(new java.awt.CardLayout());

        pnlGridView.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 5, 1));
        pnlGridView.setName(""); // NOI18N
        pnlGridView.setLayout(new java.awt.BorderLayout());

        scrpnlGrid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                scrpnlGridMouseReleased(evt);
            }
        });

        tblObjects.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblObjects.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblObjects.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblObjectsMouseReleased(evt);
            }
        });
        scrpnlGrid.setViewportView(tblObjects);

        pnlGridView.add(scrpnlGrid, java.awt.BorderLayout.CENTER);

        pnlGrid.add(pnlGridView, "cardGrid");

        pnlDetailView.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 5, 1));
        pnlDetailView.setLayout(new java.awt.BorderLayout());

        pnlInformation.setLayout(new java.awt.BorderLayout());

        lblObjectName.setText("Nome objeto: ");
        lblObjectName.setToolTipText("");
        pnlSQLInformation.add(lblObjectName);

        txtObjectName.setEnabled(false);
        txtObjectName.setPreferredSize(new java.awt.Dimension(170, 20));
        pnlSQLInformation.add(txtObjectName);

        lblObjectType.setText("Tipo objeto: ");
        pnlSQLInformation.add(lblObjectType);

        cmbBoxObjectType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlSQLInformation.add(cmbBoxObjectType);

        lblObjectDate.setText("Data inserção: ");
        pnlSQLInformation.add(lblObjectDate);

        txtObjectDate.setEnabled(false);
        txtObjectDate.setPreferredSize(new java.awt.Dimension(90, 20));
        pnlSQLInformation.add(txtObjectDate);

        lblObjectUser.setText("Usuário: ");
        pnlSQLInformation.add(lblObjectUser);

        txtObjectUser.setEnabled(false);
        txtObjectUser.setPreferredSize(new java.awt.Dimension(80, 20));
        pnlSQLInformation.add(txtObjectUser);

        pnlInformation.add(pnlSQLInformation, java.awt.BorderLayout.WEST);

        pnlDetailView.add(pnlInformation, java.awt.BorderLayout.NORTH);

        pnlSQL.setLayout(new java.awt.BorderLayout());

        txtareaSQL.setColumns(20);
        txtareaSQL.setRows(5);
        txtareaSQL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtareaSQLMouseReleased(evt);
            }
        });
        scrpnlDetail.setViewportView(txtareaSQL);

        pnlSQL.add(scrpnlDetail, java.awt.BorderLayout.CENTER);

        jToolBar1.setRollover(true);
        pnlSQL.add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        pnlDetailView.add(pnlSQL, java.awt.BorderLayout.CENTER);

        pnlGrid.add(pnlDetailView, "cardDetail");

        tbdpanelMain.addTab("Objetos", pnlGrid);

        pnlHistory.setLayout(new java.awt.BorderLayout());

        pnlObjectHistory.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 5, 1));
        pnlObjectHistory.setLayout(new java.awt.BorderLayout());

        tblObjectHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblObjectHistory.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        scrpnlHistoryGrid.setViewportView(tblObjectHistory);

        pnlObjectHistory.add(scrpnlHistoryGrid, java.awt.BorderLayout.CENTER);

        txtareaHistoryContent.setEditable(false);
        txtareaHistoryContent.setColumns(20);
        txtareaHistoryContent.setRows(5);
        scrpnlHistoryContent.setViewportView(txtareaHistoryContent);

        pnlObjectHistory.add(scrpnlHistoryContent, java.awt.BorderLayout.SOUTH);

        pnlHistory.add(pnlObjectHistory, java.awt.BorderLayout.CENTER);

        tbdpanelMain.addTab("Histórico", pnlHistory);

        pnlMain.add(tbdpanelMain, java.awt.BorderLayout.CENTER);
        tbdpanelMain.getAccessibleContext().setAccessibleName("tbtPaneMain");

        btnNew.setMnemonic('N');
        btnNew.setText("Novo");
        btnNew.setToolTipText("");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnSave.setMnemonic('S');
        btnSave.setText("Salvar");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUndo.setMnemonic('D');
        btnUndo.setText("Desfazer");
        btnUndo.setEnabled(false);
        btnUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUndoActionPerformed(evt);
            }
        });

        btnDetail.setMnemonic('h');
        btnDetail.setText("Detalhe");
        btnDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailActionPerformed(evt);
            }
        });

        btnInactivate.setMnemonic('I');
        btnInactivate.setText("Inativar");
        btnInactivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInactivateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlButtonsLayout = new javax.swing.GroupLayout(pnlButtons);
        pnlButtons.setLayout(pnlButtonsLayout);
        pnlButtonsLayout.setHorizontalGroup(
            pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUndo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInactivate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlButtonsLayout.setVerticalGroup(
            pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlButtonsLayout.createSequentialGroup()
                .addContainerGap(401, Short.MAX_VALUE)
                .addComponent(btnNew)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUndo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDetail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInactivate)
                .addGap(17, 17, 17))
        );

        pnlMain.add(pnlButtons, java.awt.BorderLayout.EAST);

        getContentPane().add(pnlMain, java.awt.BorderLayout.CENTER);

        menuUser.setText("Usuários");

        menuItemUser.setText("Usuários");
        menuItemUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemUserActionPerformed(evt);
            }
        });
        menuUser.add(menuItemUser);

        menuPassword.setText("Trocar senha");
        menuPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPasswordActionPerformed(evt);
            }
        });
        menuUser.add(menuPassword);

        menuBar.add(menuUser);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        Utilities.objectEnabledControl(false, getBtnNew(), getBtnDetail());
        Utilities.objectEnabledControl(true, getBtnSave(), getBtnUndo());
        setIsCreatingMode(true);
        setBtnInactivateEnabledWithValidation(false);
        loadObjectTypeComboBox();
        fillFieldsEmptyText();
        enabledAllFields(true);
        if ("cardGrid".equalsIgnoreCase(getSelectedCard())) {
            changeCard();
        }
        controlEditButton();
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (isEditingMode() || isCreatingMode()) {
            if ("".equalsIgnoreCase(getTxtObjectDate().getText())) {
                if (createObjectInDatabase() == 2) {

                    int cdObjectType = -1;
                    Object objectType = DAO.selectFromDatabase(Constantes.Const.SQL.SELECT_OBJECT_TYPES_CODE.getSqlCode(), getCmbBoxObjectType().getItemAt(getCmbBoxObjectType().getSelectedIndex()));
                    if (objectType instanceof ResultSet) {
                        try {
                            if (((ResultSet) objectType).next()) {
                                cdObjectType = ((ResultSet) objectType).getInt("object_code");
                            }
                        } catch (SQLException ex) {
                            Logger.getLogger(DictionaryFrame.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        Object insertDatabase = DAO.insertIntoDatabase(Constantes.Const.SQL.INSERT_OBJECT.getSqlCode(), getTxtObjectName().getText(), cdObjectType, getTxtAreaSQL().getText(), UserInstance.getUsuarioAtivo(), UserInstance.getUsuarioAtivo());
                        if (insertDatabase instanceof Integer) {
                            if ((int) insertDatabase == 0) {
                                JOptionPane.showMessageDialog(this, Expressions.DAO_RETURN.INSERT_RETURN_FAIL.getExpression());
                            } else {
                                Utilities.objectEnabledControl(false, getBtnSave(), getBtnUndo());
                                Utilities.objectEnabledControl(true, getBtnNew(), getBtnDetail());
                                setBtnInactivateEnabledWithValidation(true);
                                fillObjectsTable(false);
                                int lastRow = getTblObjects().convertRowIndexToView(getTblObjects().getModel().getRowCount() - 1);
                                getTblObjects().setRowSelectionInterval(lastRow, lastRow);
                                fillFieldsFromObject();
                                JOptionPane.showMessageDialog(this, Expressions.DAO_RETURN.VALIDATE_RETURN_OK.getExpression());
                            }
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, Expressions.DAO_RETURN.SELECT_RETURN_FAIL.getExpression() + (String) objectType);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, Expressions.DAO_RETURN.VALIDATE_RETURN_FAIL.getExpression());
                }
            } else if (createObjectInDatabase() == 2) {
                Object insertDatabase = DAO.updateRegisterDatabase(Constantes.Const.SQL.UPDATE_OBJECT.getSqlCode(), getTxtAreaSQL().getText(), UserInstance.getUsuarioAtivo(), getTblObjects().getValueAt(getTblObjects().getSelectedRow(), 0));
                if (insertDatabase instanceof Integer) {
                    if ((int) insertDatabase == 0) {
                        JOptionPane.showMessageDialog(this, Expressions.DAO_RETURN.UPDATE_RETURN_FAIL.getExpression());
                    } else {
                        Utilities.objectEnabledControl(false, getBtnSave(), getBtnUndo());
                        Utilities.objectEnabledControl(true, getBtnNew(), getBtnDetail());
                        setBtnInactivateEnabledWithValidation(true);
                        fillObjectsTable(false);
                        int lastRow = getTblObjects().convertRowIndexToView(getTblObjects().getModel().getRowCount() - 1);
                        getTblObjects().setRowSelectionInterval(lastRow, lastRow);
                        fillFieldsFromObject();
                    }
                }
                changeCard();
                setIsEditingMode(false);
                setIsCreatingMode(false);
                JOptionPane.showMessageDialog(this, Expressions.DAO_RETURN.VALIDATE_RETURN_OK.getExpression());
            }
        } else {
            setIsEditingMode(true);
            Utilities.objectEnabledControl(false, getTxtObjectName(), getCmbBoxObjectType(), getBtnNew(), getBtnDetail());
            Utilities.objectEnabledControl(true, getBtnUndo());
            fillFieldsFromObject();
            loadObjectTypeComboBox(true);
            changeCardToGrid(false);
        }
        controlEditButton();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUndoActionPerformed
        Utilities.objectEnabledControl(true, getBtnNew());
        Utilities.objectEnabledControl(false, getBtnSave(), getBtnUndo());
        Utilities.objectEnabledControl(getTblObjects().getSelectedRow() > -1, getBtnDetail());
        setIsEditingMode(false);
        setIsCreatingMode(false);
        setBtnInactivateEnabledWithValidation(getTblObjects().getSelectedRow() > -1);
        changeCardToGrid(true); // Alterar 
        controlEditButton();
    }//GEN-LAST:event_btnUndoActionPerformed

    private void btnDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailActionPerformed
        if ("cardDetail".equalsIgnoreCase(getSelectedCard())) {
            getBtnDetail().setText(Expressions.COMPONENTS.DETAIL.getExpression());
        } else {
            getBtnDetail().setText(Expressions.COMPONENTS.GRID.getExpression());
        }
        changeCard();
        fillFieldsFromObject();
        loadObjectTypeComboBox(true);
        controlEditButton();
        Utilities.objectEnabledControl((Boolean) getTblObjects().getModel().getValueAt(getTblObjects().getSelectedRow(), 11), getBtnSave());
    }//GEN-LAST:event_btnDetailActionPerformed

    private void btnInactivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInactivateActionPerformed
        String objectName = "";
        String message = "";
        if ("cardDetail".equalsIgnoreCase(getSelectedCard())) {
            objectName = getTxtObjectName().getText();
        } else {
            objectName = String.valueOf(getTblObjects().getValueAt(getTblObjects().getSelectedRow(), 1));
        }
        if (Expressions.COMPONENTS.ACTIVATE.getExpression().equalsIgnoreCase(getBtnInactivate().getText())) {
            message = "Deseja ativar o objeto " + objectName + "?";
        } else {
            message = "Deseja inaativar o objeto " + objectName + "?";
        }
        int ieConfrma = JOptionPane.showConfirmDialog(getDicFrame(), message, "", JOptionPane.YES_NO_OPTION);
        if (ieConfrma == JOptionPane.YES_OPTION) {
            if (Expressions.COMPONENTS.ACTIVATE.getExpression().equalsIgnoreCase(getBtnInactivate().getText())) {
                if (createObjectInDatabase() == 2) {
                    Object createInDatabase = DAO.updateRegisterDatabase(Constantes.Const.SQL.UPDATE_OBJECT_FLAG.getSqlCode(), 1, getTblObjects().getValueAt(getTblObjects().getSelectedRow(), 0));
                    if (createInDatabase instanceof Integer) {
                        if ((int) createInDatabase == 0) {
                            JOptionPane.showMessageDialog(this, Expressions.DAO_RETURN.UPDATE_RETURN_FAIL.getExpression());
                        } else {
                            if ("cardDetail".equalsIgnoreCase(getSelectedCard())) {
                                changeCard();
                            }
                            fillObjectsTable();
                            int lastRow = getTblObjects().convertRowIndexToView(getTblObjects().getModel().getRowCount() - 1);
                            getTblObjects().setRowSelectionInterval(lastRow, lastRow);
                            Utilities.objectEnabledControl(getTblObjects().getRowCount() > 0, getBtnDetail());
                            setBtnInactivateEnabledWithValidation(getTblObjects().getRowCount() > 0);
                            JOptionPane.showMessageDialog(this, Expressions.DAO_RETURN.ACTIVATE_RETURN_OK.getExpression());
                        }
                    }
                }
            } else if (deleteObjectInDatabase() == 0) {
                Object deleteFromDatabase = DAO.updateRegisterDatabase(Constantes.Const.SQL.UPDATE_OBJECT_FLAG.getSqlCode(), 0, getTblObjects().getValueAt(getTblObjects().getSelectedRow(), 0));
                if (deleteFromDatabase instanceof Integer) {
                    if ((int) deleteFromDatabase == 0) {
                        JOptionPane.showMessageDialog(this, Expressions.DAO_RETURN.UPDATE_RETURN_FAIL.getExpression());
                    } else {
                        if ("cardDetail".equalsIgnoreCase(getSelectedCard())) {
                            changeCard();
                        }
                        fillObjectsTable();
                        int lastRow = getTblObjects().convertRowIndexToView(getTblObjects().getModel().getRowCount() - 1);
                        getTblObjects().setRowSelectionInterval(lastRow, lastRow);
                        Utilities.objectEnabledControl(getTblObjects().getRowCount() > 0, getBtnDetail());
                        setBtnInactivateEnabledWithValidation(getTblObjects().getRowCount() > 0);
                        JOptionPane.showMessageDialog(this, Expressions.DAO_RETURN.INACTIVATE_RETUNR_OK.getExpression());
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, Expressions.DAO_RETURN.DELETE_RETURN_FAIL.getExpression());
            }
        }
    }//GEN-LAST:event_btnInactivateActionPerformed

    private void menuItemUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemUserActionPerformed
        UserFrame userFr = new UserFrame(getDicFrame());
        SwingUtilities.invokeLater(() -> (userFr.setConfiguration()));
        Utilities.objectVisibilityControl(true, userFr);
        Utilities.objectVisibilityControl(false, getDicFrame());
    }//GEN-LAST:event_menuItemUserActionPerformed

    private void createTemplateJMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createTemplateJMIActionPerformed
        callCreateTemplate();
    }//GEN-LAST:event_createTemplateJMIActionPerformed

    private void insertIfJMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertIfJMIActionPerformed
        DictionaryFrameController.addIf(getTxtAreaSQL());
    }//GEN-LAST:event_insertIfJMIActionPerformed

    private void insertIfElseJMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertIfElseJMIActionPerformed
        DictionaryFrameController.addIfElse(getTxtAreaSQL());
    }//GEN-LAST:event_insertIfElseJMIActionPerformed

    private void txtareaSQLMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtareaSQLMouseReleased
        if (evt.getButton() == MouseEvent.BUTTON3 && getTxtAreaSQL().isEnabled()) {
            getAuxJPM().show(this, evt.getX() + 20, evt.getY() + 20);
        }
    }//GEN-LAST:event_txtareaSQLMouseReleased

    private void validateObjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validateObjectActionPerformed
        validateObject();
    }//GEN-LAST:event_validateObjectActionPerformed

    private void tbdpanelMainStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tbdpanelMainStateChanged
        if (((JTabbedPane) evt.getSource()).getSelectedComponent().equals(getPnlHistory())) {
            getPnlButtons().setVisible(false);
        } else {
            getPnlButtons().setVisible(true);
        }
    }//GEN-LAST:event_tbdpanelMainStateChanged

    private void tblObjectsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblObjectsMouseReleased
        objectsMenuItem(evt);
    }//GEN-LAST:event_tblObjectsMouseReleased

    private void scrpnlGridMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scrpnlGridMouseReleased
        objectsMenuItem(evt);
    }//GEN-LAST:event_scrpnlGridMouseReleased

    private void allJMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allJMIActionPerformed
        setSearchMode('T');
        fillObjectsTable();
    }//GEN-LAST:event_allJMIActionPerformed

    private void onlyActiveJMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onlyActiveJMIActionPerformed
        setSearchMode('A');
        fillObjectsTable();
    }//GEN-LAST:event_onlyActiveJMIActionPerformed

    private void onlyInactiveJMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onlyInactiveJMIActionPerformed
        setSearchMode('I');
        fillObjectsTable();
    }//GEN-LAST:event_onlyInactiveJMIActionPerformed

    private void menuPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPasswordActionPerformed
        UserNewPassword userPwFr = new UserNewPassword(getDicFrame());
        SwingUtilities.invokeLater(() -> (userPwFr.setConfiguration()));
        Utilities.objectVisibilityControl(true, userPwFr);
    }//GEN-LAST:event_menuPasswordActionPerformed

    private void objectsMenuItem(MouseEvent evt) {
        if (evt.getButton() == MouseEvent.BUTTON3 && getTblObjects().getSelectedRow() > -1) {
            getOnlyActiveJMI().setVisible(getSearchMode() != 'A');
            getOnlyInactiveJMI().setVisible(getSearchMode() != 'I');
            getAllJMI().setVisible(getSearchMode() != 'T');
            getObjectsJPM().show(this, evt.getX() + 20, evt.getY() + 20);
        }
    }

    private void validateObject() {
        int status = createObjectInDatabase();
        switch (status) {
            case 0: {
                JOptionPane.showMessageDialog(this, Expressions.DAO_RETURN.DELETE_RETURN_FAIL.getExpression());
                break;
            }
            case 1: {
                JOptionPane.showMessageDialog(this, Expressions.DAO_RETURN.VALIDATE_RETURN_FAIL.getExpression());
                break;
            }
            case 2: {
                JOptionPane.showMessageDialog(this, Expressions.DAO_RETURN.VALIDATE_RETURN_OK.getExpression());
            }
        }
    }

    private int deleteObjectInDatabase() {
        String objectName = "";
        if ("cardDetail".equalsIgnoreCase(getSelectedCard())) {
            objectName = getTxtObjectName().getText();
        } else {
            objectName = String.valueOf(getTblObjects().getValueAt(getTblObjects().getSelectedRow(), 1));
        }
        Object delete = DAO.updateRegisterDatabase(DictionaryFrameController.getDropClause(objectName, isProcedure(), isFunction(), isTrigger()));
        if (delete instanceof Integer) {
            if ((int) delete == 1 || (int) delete == 0) {
                return 0;
            }
        }
        return -1;
    }

    private int createObjectInDatabase() {
        if (deleteObjectInDatabase() == -1) {
            return 0;
        }
        String objectContent = "";
        if ("cardDetail".equalsIgnoreCase(getSelectedCard())) {
            objectContent = getTxtAreaSQL().getText();
        } else {
            objectContent = String.valueOf(getTblObjects().getModel().getValueAt(getTblObjects().getSelectedRow(), 4)); 
        }
        Object creating = DAO.updateRegisterDatabase(objectContent);
        if (creating instanceof Integer) {
            return (int) creating == 1 ? 1 : 2;
        }
        return -1;
    }

    private void callCreateTemplate() {
        getTxtAreaSQL().append(DictionaryFrameController.getProcedureFunctionTriggerTemplate(getTxtObjectName().getText(), isProcedure(), isFunction(), isTrigger()));
    }

    private boolean isProcedure() {
        String objectName = "";
        if ("cardDetail".equalsIgnoreCase(getSelectedCard())) {
            objectName = String.valueOf(getCmbBoxObjectType().getSelectedItem());
        } else {
            objectName = String.valueOf(getTblObjects().getValueAt(getTblObjects().getSelectedRow(), 2));
        }
        return (Utilities.validaString(objectName).equalsIgnoreCase(Expressions.COMPONENTS.PROCEDURE_UPPER.getExpression()));
    }

    private boolean isFunction() {
        String objectName = "";
        if ("cardDetail".equalsIgnoreCase(getSelectedCard())) {
            objectName = String.valueOf(getCmbBoxObjectType().getSelectedItem());
        } else {
            objectName = String.valueOf(getTblObjects().getValueAt(getTblObjects().getSelectedRow(), 2));
        }
        return (Utilities.validaString(objectName).equalsIgnoreCase(Expressions.COMPONENTS.FUNCTION_UPPER.getExpression()));
    }

    private boolean isTrigger() {
        String objectName = "";
        if ("cardDetail".equalsIgnoreCase(getSelectedCard())) {
            objectName = String.valueOf(getCmbBoxObjectType().getSelectedItem());
        } else {
            objectName = String.valueOf(getTblObjects().getValueAt(getTblObjects().getSelectedRow(), 2));
        }
        return (Utilities.validaString(objectName).equalsIgnoreCase(Expressions.COMPONENTS.TRIGGER_UPPER.getExpression()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem allJMI;
    private javax.swing.JPopupMenu auxJPM;
    private javax.swing.JButton btnDetail;
    private javax.swing.JButton btnInactivate;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUndo;
    private javax.swing.JComboBox<String> cmbBoxObjectType;
    private javax.swing.JMenuItem createTemplateJMI;
    private javax.swing.JMenu filtersJMenu;
    private javax.swing.JMenuItem insertIfElseJMI;
    private javax.swing.JMenuItem insertIfJMI;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblObjectDate;
    private javax.swing.JLabel lblObjectName;
    private javax.swing.JLabel lblObjectType;
    private javax.swing.JLabel lblObjectUser;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuItemUser;
    private javax.swing.JMenuItem menuPassword;
    private javax.swing.JMenu menuUser;
    private javax.swing.JPopupMenu objectsJPM;
    private javax.swing.JMenuItem onlyActiveJMI;
    private javax.swing.JMenuItem onlyInactiveJMI;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JPanel pnlDetailView;
    private javax.swing.JPanel pnlGrid;
    private javax.swing.JPanel pnlGridView;
    private javax.swing.JPanel pnlHistory;
    private javax.swing.JPanel pnlInformation;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlObjectHistory;
    private javax.swing.JPanel pnlSQL;
    private javax.swing.JPanel pnlSQLInformation;
    private javax.swing.JScrollPane scrpnlDetail;
    private javax.swing.JScrollPane scrpnlGrid;
    private javax.swing.JScrollPane scrpnlHistoryContent;
    private javax.swing.JScrollPane scrpnlHistoryGrid;
    private javax.swing.JPopupMenu.Separator separador1JS;
    private javax.swing.JPopupMenu.Separator separador2JS;
    private javax.swing.JTabbedPane tbdpanelMain;
    private javax.swing.JTable tblObjectHistory;
    private javax.swing.JTable tblObjects;
    private javax.swing.JTextField txtObjectDate;
    private javax.swing.JTextField txtObjectName;
    private javax.swing.JTextField txtObjectUser;
    private javax.swing.JTextArea txtareaHistoryContent;
    private javax.swing.JTextArea txtareaSQL;
    private javax.swing.JMenuItem validateObject;
    // End of variables declaration//GEN-END:variables

    public void setConfiguration() {
        setDicFrameConfiguration();
        getTbdpanelMain().addChangeListener((ChangeEvent e) -> {
            if (e.getSource() instanceof JTabbedPane) {
                JTabbedPane selectedPane = (JTabbedPane) e.getSource();
                if (1 == selectedPane.getSelectedIndex()) {
                    getScrpnlHistoryContent().setPreferredSize(new Dimension(getDicFrame().getWidth(), 500));
                    fillHistoryTable(true);
                    getTxtareaHistoryContent().setText(String.valueOf(getTblObjectHistory().getModel().getValueAt(getTblObjectHistory().getSelectedRow(), 2)));
                }
                Utilities.objectEnabledControl(0 == selectedPane.getSelectedIndex(), getBtnNew(), getBtnDetail());
                setBtnInactivateEnabledWithValidation(0 == selectedPane.getSelectedIndex());
            }
        });

        getTblObjects().getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
            EventQueue.invokeLater(() -> {
                getBtnInactivate().setText(((Boolean) getTblObjects().getModel().getValueAt(getTblObjects().getSelectedRow(), 11)) ? Expressions.COMPONENTS.INACTIVATE.getExpression() : Expressions.COMPONENTS.ACTIVATE.getExpression());
                Utilities.objectEnabledControl((Boolean) getTblObjects().getModel().getValueAt(getTblObjects().getSelectedRow(), 11), getBtnSave());
            });
        });
        getTblObjectHistory().getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
            EventQueue.invokeLater(() -> {
                getTxtareaHistoryContent().setText(String.valueOf(getTblObjectHistory().getModel().getValueAt(getTblObjectHistory().getSelectedRow(), 2)));
            });
        });
        getTblObjects().addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent mouseEvent) {
                JTable table = (JTable) mouseEvent.getSource();
                Point point = mouseEvent.getPoint();
                int row = table.rowAtPoint(point);
                if (mouseEvent.getClickCount() == 2 && table.getSelectedRow() != -1) {
                    getBtnSave().doClick();
                }
            }
        });
        fillObjectsTable();
        setButtonsConfiguration();
        setCardLayout((CardLayout) getPnlGrid().getLayout());
    }

    private void setDicFrameConfiguration() {
        getDicFrame().setLocationRelativeTo(null);
        getDicFrame().setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        getDicFrame().setResizable(false);
        Rectangle usableBounds = SunGraphicsEnvironment.getUsableBounds(getDicFrame().getGraphicsConfiguration().getDevice());
        setMaximizedBounds(usableBounds);
        setExtendedState(MAXIMIZED_BOTH);
        getDicFrame().addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                Utilities.objectVisibilityControl(true, getParentFrame());
                getParentFrame().dispose();
            }
        });
    }

    private void setButtonsConfiguration() {
        getBtnDetail().setEnabled(getTblObjects().getRowCount() > 0);
        setBtnInactivateEnabledWithValidation(getTblObjects().getRowCount() > 0);
    }

    private void fillObjectsTable() {
        fillObjectsTable(true);
    }

    private void fillObjectsTable(boolean selectFirstRow) {
        Object rs = null;

        switch (getSearchMode()) {
            case 'T': {
                rs = DAO.selectFromDatabase(Constantes.Const.SQL.SELECT_ALL_DICTIONARY.getSqlCode());
                break;
            }
            case 'A': {
                rs = DAO.selectFromDatabase(Constantes.Const.SQL.SELECT_ONLY_ACTIVE_DICTIONARY.getSqlCode());
                break;
            }
            case 'I': {
                rs = DAO.selectFromDatabase(Constantes.Const.SQL.SELECT_ONLY_INACTIVE_DICTIONARY.getSqlCode());
                break;
            }
        }
        if (rs instanceof ResultSet) {
            while (getTblObjects().getRowCount() > 0) {
                ((DefaultTableModel) getTblObjects().getModel()).removeRow(0);
            }
            ((DefaultTableModel) getTblObjects().getModel()).setColumnCount(0);

            ResultSetMetaData rsMd = null;
            int columns = 0;
            try {
                rsMd = (ResultSetMetaData) ((ResultSet) rs).getMetaData();
                columns = rsMd.getColumnCount();

                for (int i = 1; i <= columns; i++) {
                    ((DefaultTableModel) getTblObjects().getModel()).addColumn(getColumnName(rsMd.getColumnLabel(i)));
                }
            } catch (SQLException ex) {
                LOGGER.info(new StringBuilder(Expressions.COMPONENTS.COLUMNN_ADD_FAIL.getExpression()).append(ex).toString());
            }

            try {
                while (((ResultSet) rs).next()) {
                    Object[] row = new Object[columns];
                    for (int i = 1; i <= columns; i++) {
                        row[i - 1] = ((ResultSet) rs).getObject(i);
                    }

                    ((DefaultTableModel) getTblObjects().getModel()).insertRow(((ResultSet) rs).getRow() - 1, row);
                }
            } catch (SQLException ex) {
                LOGGER.info(new StringBuilder(Expressions.COMPONENTS.ROW_ADD_FAIL.getExpression()).append(ex).toString());
            }
            getTblObjects().getColumnModel().getColumn(5).setCellRenderer(tableCellRenderer);
            getTblObjects().getColumnModel().getColumn(8).setCellRenderer(tableCellRenderer);
            getTblObjects().getColumnModel().getColumn(11).setCellRenderer(tableCellRenderer);
            getTblObjects().getColumnModel().removeColumn(getTblObjects().getColumnModel().getColumn(9));
            getTblObjects().getColumnModel().removeColumn(getTblObjects().getColumnModel().getColumn(6));
            getTblObjects().getColumnModel().removeColumn(getTblObjects().getColumnModel().getColumn(4));
            getTblObjects().getColumnModel().removeColumn(getTblObjects().getColumnModel().getColumn(2));
            adjustTableColumns(getTblObjects().getColumnModel());
            if (selectFirstRow) {
                getTblObjects().getSelectionModel().setSelectionInterval(0, 0);
            }
        }
    }

    private void adjustTableColumns(TableColumnModel columnModel) {
        for (int i = 0; i < columnModel.getColumnCount(); i++) {
            int width = String.valueOf(columnModel.getColumn(i).getHeaderValue()).length();
            columnModel.getColumn(i).setPreferredWidth(width * 10);
        }
    }

    private void fillHistoryTable() {
        fillHistoryTable(true);
    }

    private void fillHistoryTable(boolean selectFirstRow) {
        Object rs = DAO.selectFromDatabase(Constantes.Const.SQL.SELECT_ALL_DICTIONARY_HISTORY.getSqlCode(), getTblObjects().getValueAt(getTblObjects().getSelectedRow(), 0));
        if (rs instanceof ResultSet) {
            while (getTblObjectHistory().getRowCount() > 0) {
                ((DefaultTableModel) getTblObjectHistory().getModel()).removeRow(0);
            }
            ((DefaultTableModel) getTblObjectHistory().getModel()).setColumnCount(0);

            ResultSetMetaData rsMd = null;
            int columns = 0;
            try {
                rsMd = (ResultSetMetaData) ((ResultSet) rs).getMetaData();
                columns = rsMd.getColumnCount();

                for (int i = 1; i <= columns; i++) {
                    ((DefaultTableModel) getTblObjectHistory().getModel()).addColumn(getColumnName(rsMd.getColumnLabel(i)));
                }
            } catch (SQLException ex) {
                LOGGER.info(new StringBuilder(Expressions.COMPONENTS.COLUMNN_ADD_FAIL.getExpression()).append(ex).toString());
            }

            try {
                while (((ResultSet) rs).next()) {
                    Object[] row = new Object[columns];
                    for (int i = 1; i <= columns; i++) {
                        row[i - 1] = ((ResultSet) rs).getObject(i);
                    }

                    ((DefaultTableModel) getTblObjectHistory().getModel()).insertRow(((ResultSet) rs).getRow() - 1, row);
                }
            } catch (SQLException ex) {
                LOGGER.info(new StringBuilder(Expressions.COMPONENTS.ROW_ADD_FAIL.getExpression()).append(ex).toString());
            }
            getTblObjectHistory().getColumnModel().getColumn(3).setCellRenderer(tableCellRenderer);
            getTblObjectHistory().getColumnModel().removeColumn(getTblObjectHistory().getColumnModel().getColumn(4));
            getTblObjectHistory().getColumnModel().removeColumn(getTblObjectHistory().getColumnModel().getColumn(2));
            getTblObjectHistory().getColumnModel().removeColumn(getTblObjectHistory().getColumnModel().getColumn(1));
            adjustTableColumns(getTblObjectHistory().getColumnModel());
            if (selectFirstRow) {
                getTblObjectHistory().getSelectionModel().setSelectionInterval(0, 0);
            }
        }
    }

    private String getColumnName(String nmColunaCampo) {
        switch (nmColunaCampo) {
            case "NR_SEQUENCE": {
                return Expressions.TABLE_COLUMNS.NR_SEQUENCE.getExpression();
            }
            case "DS_NAME": {
                return Expressions.TABLE_COLUMNS.DS_NAME.getExpression();
            }
            case "DS_TYPE": {
                return Expressions.TABLE_COLUMNS.DS_TYPE.getExpression();
            }
            case "DT_INSERTION": {
                return Expressions.TABLE_COLUMNS.DT_INSERTION.getExpression();
            }
            case "DT_UPDATE": {
                return Expressions.TABLE_COLUMNS.DT_UPDATE.getExpression();
            }
            case "DT_INSERTION_HISTORY": {
                return Expressions.TABLE_COLUMNS.DT_INSERTION_HISTORY.getExpression();
            }
            case "DS_USER": {
                return Expressions.TABLE_COLUMNS.DS_USER.getExpression();
            }
            case "DS_USER_UPDATE": {
                return Expressions.TABLE_COLUMNS.DS_USER_UPDATE.getExpression();
            }
            case "DS_USER_HIST": {
                return Expressions.TABLE_COLUMNS.DS_USER_HIST.getExpression();
            }
            case "IS_ACTIVE": {
                return Expressions.TABLE_COLUMNS.IS_ACTIVE.getExpression();
            }
        }
        return Expressions.TABLE_COLUMNS.NOT_A_COLUMN.getExpression();
    }

    private void changeCard() {
        if ("cardDetail".equalsIgnoreCase(getSelectedCard())) {
            setSelectedCard("cardGrid");
        } else {
            setSelectedCard("cardDetail");
        }
        getCardLayout().show(getPnlGrid(), getSelectedCard());
    }

    private void changeCardToGrid(boolean toGrid) {
        if (toGrid) {
            setSelectedCard("cardGrid");
        } else {
            setSelectedCard("cardDetail");
        }
        getCardLayout().show(getPnlGrid(), getSelectedCard());
    }

    private void loadObjectTypeComboBox() {
        loadObjectTypeComboBox(false);
    }

    private void loadObjectTypeComboBox(boolean selectRecord) {
        String selectType = "";
        if (selectRecord && getCmbBoxObjectType().getSelectedItem() != null) {
            selectType = String.valueOf(getCmbBoxObjectType().getSelectedItem());
        }
        Object objectTypes = DAO.selectFromDatabase(Constantes.Const.SQL.SELECT_OBJECT_TYPES.getSqlCode());
        if (objectTypes instanceof ResultSet) {
            DefaultComboBoxModel comboBoxModel = new DefaultComboBoxModel();
            List<String> types = new ArrayList<>();
            try {
                while (((ResultSet) objectTypes).next()) {
                    types.add(((ResultSet) objectTypes).getString("ds_object_type"));
                }
            } catch (SQLException ex) {
                LOGGER.info(new StringBuilder().append(Expressions.DAO_RETURN.SELECT_RETURN_FAIL).append(ex).toString());
            }
            for (final String i : types) {
                EventQueue.invokeLater(() -> {
                    comboBoxModel.addElement(i);
                });
            }
            getCmbBoxObjectType().setModel(comboBoxModel);
            if (selectRecord) {
                final String selectTypeW = selectType;
                SwingUtilities.invokeLater(() -> {
                    getCmbBoxObjectType().setSelectedItem(selectTypeW);
                });
            }
        }
    }

    private void fillFieldsEmptyText() {
        String str = "";
        getTxtObjectName().setText(str);
        getCmbBoxObjectType().setSelectedItem(null);
        getTxtObjectDate().setText(str);
        getTxtObjectUser().setText(str);
        getTxtAreaSQL().setText(str);
    }

    private void fillFieldsFromObject() {
        String str = "";
        str = String.valueOf(getTblObjects().getModel().getValueAt(getTblObjects().getSelectedRow(), 1));
        getTxtObjectName().setText(str);
        str = String.valueOf(getTblObjects().getModel().getValueAt(getTblObjects().getSelectedRow(), 3));
        getCmbBoxObjectType().setSelectedItem(String.valueOf(str));
        str = String.valueOf(getTblObjects().getModel().getValueAt(getTblObjects().getSelectedRow(), 4));
        getTxtAreaSQL().setText(str);
        str = String.valueOf(getTblObjects().getModel().getValueAt(getTblObjects().getSelectedRow(), 5));
        getTxtObjectDate().setText(str);
        str = String.valueOf(getTblObjects().getModel().getValueAt(getTblObjects().getSelectedRow(), 7));
        getTxtObjectUser().setText(str);
    }

    private void enabledAllFields(boolean enabled) {
        getTxtObjectName().setEnabled(enabled);
        getCmbBoxObjectType().setEnabled(enabled);
        getTxtAreaSQL().setEnabled(enabled);
    }

    private void setBtnInactivateEnabledWithValidation(boolean setActivate) {
        Utilities.objectEnabledControl(UserInstance.isAdmin() && setActivate, getBtnInactivate());
    }

    private void controlEditButton() {
        if (isCreatingMode() || isEditingMode()) {
            getBtnSave().setText(Expressions.COMPONENTS.SAVE.getExpression());
            Utilities.objectEnabledControl(!getBtnNew().isEnabled(), getTxtAreaSQL());
        } else {
            getBtnSave().setText(Expressions.COMPONENTS.EDIT.getExpression());
            Utilities.objectEnabledControl(!getBtnNew().isEnabled(), getTxtAreaSQL(), getCmbBoxObjectType());
            Utilities.objectEnabledControl(getBtnNew().isEnabled(), getBtnSave());
        }
    }

    private void controlInactiveButton() {
        Utilities.objectEnabledControl(getTblObjects().getSelectedRow() > -1 && UserInstance.isAdmin(), getBtnUndo());
    }

    public DictionaryFrame getDicFrame() {
        return this;
    }

    public JTable getTblObjects() {
        return tblObjects;
    }

    public JTable getTblObjectHistory() {
        return tblObjectHistory;
    }

    public String getSelectedCard() {
        return selectedCard;
    }

    public void setSelectedCard(String selectedCard) {
        this.selectedCard = selectedCard;
    }

    public CardLayout getCardLayout() {
        return cardLayout;
    }

    public void setCardLayout(CardLayout cardLayout) {
        this.cardLayout = cardLayout;
    }

    public JPanel getPnlGrid() {
        return pnlGrid;
    }

    public JButton getBtnDetail() {
        return btnDetail;
    }

    public JButton getBtnNew() {
        return btnNew;
    }

    public JButton getBtnSave() {
        return btnSave;
    }

    public JButton getBtnUndo() {
        return btnUndo;
    }

    public JButton getBtnInactivate() {
        return btnInactivate;
    }

    public JTextField getTxtObjectDate() {
        return txtObjectDate;
    }

    public JTextField getTxtObjectName() {
        return txtObjectName;
    }

    public JTextField getTxtObjectUser() {
        return txtObjectUser;
    }

    public JTextArea getTxtAreaSQL() {
        return txtareaSQL;
    }

    public JTabbedPane getTbdpanelMain() {
        return tbdpanelMain;
    }

    public JTextArea getTxtareaHistoryContent() {
        return txtareaHistoryContent;
    }

    public JScrollPane getScrpnlHistoryContent() {
        return scrpnlHistoryContent;
    }

    public JComboBox<String> getCmbBoxObjectType() {
        return cmbBoxObjectType;
    }

    public JMenuItem getMenuItemUser() {
        return menuItemUser;
    }

    public boolean isCreatingMode() {
        return isCreatingMode;
    }

    public void setIsCreatingMode(boolean isCreatingMode) {
        this.isCreatingMode = isCreatingMode;
    }

    public boolean isEditingMode() {
        return isEditingMode;
    }

    public void setIsEditingMode(boolean isEditingMode) {
        this.isEditingMode = isEditingMode;
    }

    public JPanel getPnlButtons() {
        return pnlButtons;
    }

    public JFrame getParentFrame() {
        return parentFrame;
    }

    public JPopupMenu getAuxJPM() {
        return auxJPM;
    }

    public JPanel getPnlHistory() {
        return pnlHistory;
    }

    public char getSearchMode() {
        return searchMode;
    }

    public void setSearchMode(char searchMode) {
        this.searchMode = searchMode;
    }

    public JMenuItem getAllJMI() {
        return allJMI;
    }

    public JMenuItem getOnlyActiveJMI() {
        return onlyActiveJMI;
    }

    public JMenuItem getOnlyInactiveJMI() {
        return onlyInactiveJMI;
    }

    public JPopupMenu getObjectsJPM() {
        return objectsJPM;
    }

}
