/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import java.awt.Component;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.WindowEvent;
import javax.swing.SwingUtilities;

/**
 *
 * @author ronyjack
 */
public class LoginFrame extends javax.swing.JFrame {

    private static LoginFrame loginInstance = null;

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editsPanel = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        lblUser = new javax.swing.JLabel();
        editPassw = new javax.swing.JPasswordField();
        lblPassw = new javax.swing.JLabel();
        buttonsPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField2.setToolTipText("Insira o usuário de login");
        jTextField2.setName("edtLogin"); // NOI18N

        lblUser.setText("Usuário:");
        lblUser.setName("lblUser"); // NOI18N

        editPassw.setToolTipText("Insira a senha do usuário para login");
        editPassw.setName("edtPassw"); // NOI18N

        lblPassw.setText("Senha:");
        lblPassw.setName("lblPassw"); // NOI18N

        javax.swing.GroupLayout editsPanelLayout = new javax.swing.GroupLayout(editsPanel);
        editsPanel.setLayout(editsPanelLayout);
        editsPanelLayout.setHorizontalGroup(
            editsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUser)
                    .addComponent(lblPassw))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editPassw, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(jTextField2))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        editsPanelLayout.setVerticalGroup(
            editsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editPassw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassw))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(editsPanel, java.awt.BorderLayout.CENTER);

        jButton1.setMnemonic('E');
        jButton1.setText("Entrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setMnemonic('S');
        jButton2.setText("Sair");
        jButton2.setMaximumSize(new java.awt.Dimension(63, 23));
        jButton2.setMinimumSize(new java.awt.Dimension(63, 23));
        jButton2.setPreferredSize(new java.awt.Dimension(63, 23));

        javax.swing.GroupLayout buttonsPanelLayout = new javax.swing.GroupLayout(buttonsPanel);
        buttonsPanel.setLayout(buttonsPanelLayout);
        buttonsPanelLayout.setHorizontalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsPanelLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        buttonsPanelLayout.setVerticalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsPanelLayout.createSequentialGroup()
                .addGroup(buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(buttonsPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Component[] componentes = loginInstance.getComponents();
        for(Component c: componentes){
            System.out.println("================");
            System.out.println("Name: " + c.getName());
            System.out.println("Name: " + c.toString());
            System.out.println("Size: " + c.getPreferredSize());
            System.out.println("Size: " + c.getMinimumSize());
            System.out.println("Size: " + c.getMaximumSize());
            System.out.println("================");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //createLookAndFeel();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            loginInstance = new LoginFrame();
            loginInstance.setConfiguration();
            loginInstance.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JPasswordField editPassw;
    private javax.swing.JPanel editsPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblPassw;
    private javax.swing.JLabel lblUser;
    // End of variables declaration//GEN-END:variables
    private static void createLookAndFeel() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    private void setConfiguration() {
        loginInstance.setLocationRelativeTo(null);
        loginInstance.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        loginInstance.setResizable(false);
        addListeners();
        SwingUtilities.invokeLater(() -> {
            //jTextField1.requestFocus();
        });
    }

    private void addListeners() {
        /*
        KeyListener enterListener = new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    jButton1ActionPerformed(null);
                }
            }
        };
        jTextField1.addKeyListener(enterListener);
        jPasswordField1.addKeyListener(enterListener);
        jButton1.addKeyListener(enterListener);

        KeyListener escListener = new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ESCAPE) {
                    getLoginFrame().dispatchEvent(new WindowEvent(getLoginFrame(), WindowEvent.WINDOW_CLOSING));
                }
            }
        };
        jTextField1.addKeyListener(escListener);
        jPasswordField1.addKeyListener(escListener);
        jButton1.addKeyListener(escListener);
        jButton2.addKeyListener(escListener);
         */
    }

}
