DROP TABLE IF EXISTS `objects_types`;
CREATE TABLE IF NOT EXISTS `objects_types` (
  `CD_OBJECT_TYPE` int(11) NOT NULL AUTO_INCREMENT,
  `DS_OBJECT_TYPE` varchar(45) NOT NULL,
  PRIMARY KEY (`CD_OBJECT_TYPE`),
  UNIQUE KEY `cd_object_type_UNIQUE` (`CD_OBJECT_TYPE`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;

/*!40000 ALTER TABLE `objects_types` DISABLE KEYS */;
INSERT INTO `objects_types` (`CD_OBJECT_TYPE`, `DS_OBJECT_TYPE`) VALUES
	(-1, 'ERROR'),
	(1, 'PROCEDURE'),
	(2, 'FUNCTION'),
	(3, 'VIEW'),
	(4, 'TRIGGER');
/*!40000 ALTER TABLE `objects_types` ENABLE KEYS */;