DROP FUNCTION IF EXISTS `getObjectTypeCode`;
DELIMITER //
CREATE DEFINER=`root`@`localhost` FUNCTION `getObjectTypeCode`(DS_TYPE_P VARCHAR(255)) RETURNS int(255)
BEGIN
  DECLARE OBJECT_RETURN INT(255);
  
  SELECT CD_OBJECT_TYPE
  INTO OBJECT_RETURN
  FROM OBJECTS_TYPES
  WHERE DS_OBJECT_TYPE = DS_TYPE_P;
  
  RETURN OBJECT_RETURN;
END//
DELIMITER ;