DROP TRIGGER IF EXISTS `dictionary_after_insert`;
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `dictionary_after_insert` AFTER INSERT ON `dictionary` FOR EACH ROW BEGIN
  INSERT INTO dictionary_history(NR_SEQ_OBJECT, DS_CONTENT, DT_INSERTION, CD_USER)
  VALUES(NEW.NR_SEQUENCE,  NEW.DS_CONTENT, SYSDATE(), NEW.CD_USER);
END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

DROP TRIGGER IF EXISTS `dictionary_after_update`;
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `dictionary_after_update` AFTER UPDATE ON `dictionary` FOR EACH ROW BEGIN
  INSERT INTO DICTIONARY_HISTORY(NR_SEQ_OBJECT, DS_CONTENT, DT_INSERTION, CD_USER)
  VALUES(NEW.NR_SEQUENCE,  NEW.DS_CONTENT, SYSDATE(), NEW.CD_USER);
END//
DELIMITER ;